name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache-dependency-path: ./pnpm-lock.lock

      - name: Setup Package Manager
        run: |
          corepack enable
          pnpm --version

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache-dependency-path: ./pnpm-lock.lock

      - name: Setup Package Manager
        run: |
          corepack enable
          pnpm --version

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
